services: 
  db: 
    image: postgres:9.6
    container_name: os_systems_db
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: os_systems
    ports: 
      - 3002:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes: 
  postgres-data:
